dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.3
  - smartcontractkit/chainlink@1.9.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.3'
      - '@chainlink=smartcontractkit/chainlink@1.9.0'
dotenv: .env
networks:
  default: development
  goerli:
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False  
wallets:
  from_key: ${PRIVATE_KEY}
